<?php
if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * Rezponz SEO Engine – Main bootstrap class.
 *
 * Registers the rzpa_pseo custom post type, manages rewrite rules,
 * outputs SEO meta tags, and controls loop visibility.
 *
 * @package Rezponz\SEOEngine
 * @since   1.0.0
 */
class RZPA_SEO_Engine {

    // ── Bootstrap ─────────────────────────────────────────────────────────────

    /**
     * Registers all WordPress hooks.
     *
     * @return void
     */
    public static function init() : void {
        add_action( 'init',              [ __CLASS__, 'register_cpt' ] );
        add_action( 'after_setup_theme', [ __CLASS__, 'flush_rewrite_if_needed' ] );
        add_action( 'wp_head',           [ __CLASS__, 'output_seo_meta' ], 1 );
        add_action( 'pre_get_posts',     [ __CLASS__, 'exclude_from_loops' ] );
        add_filter( 'the_posts',         [ __CLASS__, 'maybe_filter_pseo_from_loop' ] );
    }

    // ── Custom Post Type ──────────────────────────────────────────────────────

    /**
     * Registers the 'rzpa_pseo' CPT for programmatic SEO landing pages.
     *
     * @return void
     */
    public static function register_cpt() : void {
        $labels = [
            'name'                  => _x( 'pSEO Sider', 'post type general name', 'rezponz-analytics' ),
            'singular_name'         => _x( 'pSEO Side', 'post type singular name', 'rezponz-analytics' ),
            'menu_name'             => _x( 'pSEO Sider', 'admin menu', 'rezponz-analytics' ),
            'name_admin_bar'        => _x( 'pSEO Side', 'add new on dashboard', 'rezponz-analytics' ),
            'add_new'               => __( 'Tilføj ny', 'rezponz-analytics' ),
            'add_new_item'          => __( 'Tilføj ny pSEO Side', 'rezponz-analytics' ),
            'new_item'              => __( 'Ny pSEO Side', 'rezponz-analytics' ),
            'edit_item'             => __( 'Rediger pSEO Side', 'rezponz-analytics' ),
            'view_item'             => __( 'Vis pSEO Side', 'rezponz-analytics' ),
            'all_items'             => __( 'Alle pSEO Sider', 'rezponz-analytics' ),
            'search_items'          => __( 'Søg pSEO Sider', 'rezponz-analytics' ),
            'parent_item_colon'     => __( 'Overordnet pSEO Side:', 'rezponz-analytics' ),
            'not_found'             => __( 'Ingen pSEO Sider fundet.', 'rezponz-analytics' ),
            'not_found_in_trash'    => __( 'Ingen pSEO Sider i papirkurven.', 'rezponz-analytics' ),
            'featured_image'        => __( 'Fremhævet billede', 'rezponz-analytics' ),
            'set_featured_image'    => __( 'Sæt fremhævet billede', 'rezponz-analytics' ),
            'remove_featured_image' => __( 'Fjern fremhævet billede', 'rezponz-analytics' ),
            'use_featured_image'    => __( 'Brug som fremhævet billede', 'rezponz-analytics' ),
            'archives'              => __( 'pSEO Side arkiv', 'rezponz-analytics' ),
            'insert_into_item'      => __( 'Indsæt i pSEO Side', 'rezponz-analytics' ),
            'uploaded_to_this_item' => __( 'Uploadet til denne pSEO Side', 'rezponz-analytics' ),
            'items_list'            => __( 'pSEO Sider liste', 'rezponz-analytics' ),
            'items_list_navigation' => __( 'pSEO Sider listenavigation', 'rezponz-analytics' ),
            'filter_items_list'     => __( 'Filtrer pSEO Sider liste', 'rezponz-analytics' ),
        ];

        $args = [
            'labels'              => $labels,
            'description'         => 'Programmatic SEO landing pages generated by Rezponz SEO Engine',
            'public'              => true,
            'publicly_queryable'  => true,
            'show_ui'             => true,
            'show_in_menu'        => false,
            'show_in_nav_menus'   => false,
            'show_in_rest'        => true,
            'query_var'           => 'rzpa_pseo',
            'rewrite'             => [
                'slug'       => self::get_rewrite_base(),
                'with_front' => false,
            ],
            'capability_type'     => 'post',
            'has_archive'         => false,
            'hierarchical'        => false,
            'exclude_from_search' => false,
            'supports'            => [ 'title', 'editor', 'excerpt', 'custom-fields', 'revisions' ],
            'menu_icon'           => 'dashicons-search',
        ];

        register_post_type( 'rzpa_pseo', $args );
    }

    /**
     * Returns the URL rewrite base slug for pSEO posts.
     *
     * Defaults to 'job'; overridable via the 'rzpa_seo_rewrite_base' option.
     *
     * @return string
     */
    public static function get_rewrite_base() : string {
        return (string) get_option( 'rzpa_seo_rewrite_base', 'job' );
    }

    /**
     * Flushes rewrite rules once if the transient flag is set.
     *
     * Call update_option('rzpa_seo_flush_rewrite', 1) to schedule a flush.
     *
     * @return void
     */
    public static function flush_rewrite_if_needed() : void {
        if ( get_option( 'rzpa_seo_flush_rewrite' ) ) {
            flush_rewrite_rules();
            delete_option( 'rzpa_seo_flush_rewrite' );
        }
    }

    // ── SEO Meta Output ───────────────────────────────────────────────────────

    /**
     * Outputs SEO meta tags in <head> for singular rzpa_pseo posts.
     *
     * Skipped when Yoast SEO or RankMath is active (they handle meta output).
     *
     * @return void
     */
    public static function output_seo_meta() : void {
        if ( ! is_singular( 'rzpa_pseo' ) ) {
            return;
        }

        // Defer to Yoast or RankMath if present.
        if ( defined( 'WPSEO_VERSION' ) || class_exists( 'RankMath' ) ) {
            return;
        }

        $post_id     = get_the_ID();
        $meta        = RZPA_SEO_Meta::get_meta( (int) $post_id );
        $title       = $meta['meta_title']       ?? '';
        $description = $meta['meta_description'] ?? '';
        $canonical   = $meta['canonical_url']    ?? '';
        $noindex     = ! empty( $meta['noindex'] );

        if ( $title ) {
            // Override document title via filter as well (handled by RZPA_SEO_Meta),
            // but also output a raw <title> as fallback inside wp_head.
            echo '<title>' . esc_html( $title ) . '</title>' . "\n";
        }

        if ( $description ) {
            echo '<meta name="description" content="' . esc_attr( $description ) . '">' . "\n";
        }

        if ( $canonical ) {
            echo '<link rel="canonical" href="' . esc_url( $canonical ) . '">' . "\n";
        } elseif ( $post_id ) {
            echo '<link rel="canonical" href="' . esc_url( get_permalink( $post_id ) ) . '">' . "\n";
        }

        if ( $noindex ) {
            echo '<meta name="robots" content="noindex,nofollow">' . "\n";
        }
    }

    // ── Loop Exclusions ───────────────────────────────────────────────────────

    /**
     * Excludes rzpa_pseo from the main query on home, feed, and archive pages.
     *
     * @param WP_Query $query
     * @return void
     */
    public static function exclude_from_loops( WP_Query $query ) : void {
        if ( is_admin() ) {
            return;
        }

        if ( ! $query->is_main_query() ) {
            return;
        }

        if ( ! ( $query->is_home() || $query->is_feed() || $query->is_archive() ) ) {
            return;
        }

        $post_type = $query->get( 'post_type' );

        // If query is not restricted to a specific type, build an exclusion list.
        if ( empty( $post_type ) || $post_type === 'any' || $post_type === 'post' ) {
            // For post_type='post', do nothing — rzpa_pseo is a separate type.
            // For empty / 'any', explicitly set post_types excluding rzpa_pseo.
            if ( empty( $post_type ) || $post_type === 'any' ) {
                $public_types = get_post_types( [ 'public' => true ] );
                unset( $public_types['rzpa_pseo'] );
                $query->set( 'post_type', array_values( $public_types ) );
            }
        }
    }

    /**
     * Secondary filter on the_posts to ensure rzpa_pseo pages are not shown
     * in standard loops that bypass pre_get_posts.
     *
     * @param WP_Post[] $posts
     * @return WP_Post[]
     */
    public static function maybe_filter_pseo_from_loop( array $posts ) : array {
        if ( is_admin() || is_singular() ) {
            return $posts;
        }

        global $wp_query;

        // Only filter on home/feed/archive main query.
        if ( ! isset( $wp_query ) || ! $wp_query->is_main_query() ) {
            return $posts;
        }

        if ( ! ( $wp_query->is_home() || $wp_query->is_feed() || $wp_query->is_archive() ) ) {
            return $posts;
        }

        return array_values(
            array_filter( $posts, static fn( WP_Post $p ) => 'rzpa_pseo' !== $p->post_type )
        );
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /**
     * Returns post count object for the rzpa_pseo CPT.
     *
     * @return object  stdClass with publish/draft/etc. properties.
     */
    public static function get_pseo_post_count() : object {
        return wp_count_posts( 'rzpa_pseo' );
    }

    /**
     * Returns the WP_Post linked to a dataset via linked_post_id.
     *
     * @param int $dataset_id
     * @return WP_Post|null
     */
    public static function get_post_by_dataset( int $dataset_id ) : ?WP_Post {
        $dataset = RZPA_SEO_DB::get_dataset( $dataset_id );
        if ( empty( $dataset['linked_post_id'] ) ) {
            return null;
        }

        $post = get_post( (int) $dataset['linked_post_id'] );
        return ( $post instanceof WP_Post ) ? $post : null;
    }
}
